RustCrypto/block-ciphers

Cargo.toml, block-modes/Cargo.toml, block-modes/src/cbc.rs, block-modes/src/cfb.rs, block-modes/src/ctr.rs, block-modes/src/lib.rs, block-modes/src/ofb.rs, block-modes/src/pcbc.rs, block-modes/src/traits.rs, block-modes/tests/lib.rs, blowfish/Cargo.toml, blowfish/src/lib.rs, kuznyechik/Cargo.toml, kuznyechik/src/lib.rs, magma/Cargo.toml, magma/src/lib.rs, rc2/Cargo.toml, rc2/src/lib.rs, rc2/tests/lib.rs, twofish/Cargo.toml, twofish/src/lib.rs, twofish/tests/lib.rs
Necessary since https://github.com/RustCrypto/traits/commit/4e4ecaf0c951995525570ed1212d43fe56c2ae7a
=> Update generic-array to 0.9

aes/aesni/src/aes128/expand.rs, aes/aesni/src/aes192/expand.rs, aes/aesni/src/aes256/expand.rs
Fixes #23 
@gnzlbg
What do you think? Do you have any suggestions where unsafe code can be improved? I will not be using `union` approach here yet, maybe I'll change my mind in future.
=> More pedantic unsafe code

twofish/src/lib.rs
The <<= operator can be used directly.
If you are OK with small fixes like this I'm happy to send more.
=> Use assign operator

aes/aes-soft/src/bitslice.rs, aes/aes-soft/src/consts.rs, aes/aes-soft/src/expand.rs, block-modes/src/cfb.rs, block-modes/src/ctr128.rs, blowfish/src/consts.rs, kuznyechik/src/lib.rs, rc2/src/lib.rs
This is cleaner and more explicit.
=> Apply clippy lints

block-modes/LICENSE-APACHE, block-modes/LICENSE-MIT
Fixes: https://github.com/RustCrypto/block-ciphers/issues/46
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
=> block-modes: add LICENSE files

README.md, block-modes/src/lib.rs
convinience -> [convenience](https://en.wiktionary.org/wiki/convenience#Noun)
=> Fix a typo

idea/Cargo.toml, serpent/Cargo.toml, sm4/CHANGELOG.md, sm4/Cargo.toml, sm4/README.md, sm4/src/lib.rs
=> sm4 v0.0.1

README.md, threefish/CHANGELOG.md, threefish/Cargo.toml, threefish/README.md, threefish/src/lib.rs
=> threefish v0.0.1

aes/aes-soft/src/impls.rs
=> aes-soft: replace transmute with pointer casts

serpent/benches/lib.rs
Results are not good:
test decrypt ... bench:       4,640 ns/iter (+/- 1,016) = 3 MB/s
test encrypt ... bench:       4,870 ns/iter (+/- 906) = 3 MB/s
=> serpent: add benchmark

aes/aesni/src/aes128/expand.rs, aes/aesni/src/aes192/expand.rs, aes/aesni/src/aes256/expand.rs, aes/aesni/src/ctr.rs
It's slightly shorter/more readable.
=> aesni: use mem::zeroed instead of MaybeUninit

aes/README.md, blowfish/README.md, cast5/README.md, des/README.md, idea/README.md, kuznyechik/README.md, magma/README.md, rc2/README.md, serpent/README.md, sm4/README.md, threefish/README.md, twofish/README.md
- Fix broken Unicode
- Link to https://github.com/RustCrypto/meta/blob/master/HAZMAT.md
=> README.md(s): update "hazmat" badges

aes/aesni/CHANGELOG.md
Information about #165 was accidentally omitted
=> aesni: update CHANGELOG.md

.github/workflows/aes-soft.yml, aes/aes-soft/src/lib.rs
- PPC32 is useful to test endianness handling
- ARM64 is good to test because it's an important platform
=> aes-soft: CI using cross for PPC32/ARM64.

aes/aes-soft/src/fixslice32.rs, aes/aes-soft/src/fixslice64.rs
- see https://github.com/Ko-/aes-armcortexm
Noticeable improvement in decryption speed from new inv_sbox. Applied same technique to sbox for consistency, though there's not as clear a benefit.
=> Re-order AES (inv)_sbox using custom scheduler

Cargo.lock, aes/Cargo.toml, aes/src/lib.rs
=> aes: use cfg-if crate

Cargo.lock, block-modes/CHANGELOG.md, block-modes/Cargo.toml, block-modes/src/ige.rs, block-modes/tests/lib.rs
Follow-up to #211. The release is blocked on finalizing and releasing `cipher v0.3` (I plan to submit some changes to it soon.).
cc @razielgn
=> IGE mode code improvements

aes/README.md
=> aes: update AES diagram in README.md

aes/CHANGELOG.md
=> aes: expand CHANGELOG information about `ctr` feature

block-modes/src/lib.rs
=> Fix a typo in the docstring

README.md
=> Fix example in toplevel README.md

README.md
I plan to reference the notice in crate docs.
=> Add README notice about higher-level constructions

Cargo.lock, aes/CHANGELOG.md, aes/Cargo.toml, aes/src/lib.rs
=> aes: fix docs around configuration flags

.github/workflows/aes.yml
https://github.com/RustCrypto/actions/tree/master/cross-install
=> CI: use `cross-install` action in `aes` workflow

Cargo.lock, rc5/CHANGELOG.md, rc5/Cargo.toml
=> rc5 v0.0.1

aes/src/armv8/expand.rs
=> aes: use const preconditions assert

README.md
=> Update information about `speck-cipher` in README

speck/CHANGELOG.md
=> speck: add initial CHANGELOG.md

.github/workflows/kuznyechik.yml, kuznyechik/src/fused_tables/consts.rs, kuznyechik/src/lib.rs
CI did not catch this issue because the job config was broken in the same PR which has introduced the bad code.
=> kuznyechik: fix zeroize imports

aes/README.md
=> aes: replace NCC Group link with Web Archive mirror

.github/workflows/security-audit.yml
The `actions-rs` action is unmaintained
=> CI: use `rustsec/audit-check@v2`

.github/workflows/aes.yml, .github/workflows/aria.yml, .github/workflows/belt-block.yml, .github/workflows/blowfish.yml, .github/workflows/camellia.yml, .github/workflows/cast5.yml, .github/workflows/cast6.yml, .github/workflows/des.yml, .github/workflows/gift.yml, .github/workflows/idea.yml, .github/workflows/kuznyechik.yml, .github/workflows/magma.yml, .github/workflows/rc2.yml, .github/workflows/rc5.yml, .github/workflows/serpent.yml, .github/workflows/sm4.yml, .github/workflows/speck.yml, .github/workflows/threefish.yml, .github/workflows/twofish.yml, .github/workflows/workspace.yml, .github/workflows/xtea.yml
Same as https://github.com/RustCrypto/traits/pull/1948.
=> Only run CI on latest commit of PR branches.

Cargo.lock, Cargo.toml, aes/tests/mod.rs, blowfish/tests/mod.rs, camellia/tests/mod.rs, cast5/tests/mod.rs, des/tests/mod.rs, idea/tests/mod.rs, serpent/tests/mod.rs
Depends on https://github.com/RustCrypto/traits/pull/1998
Closes #501
=> Migrate to new dev macro
