RustCrypto/block-ciphers

blowfish/Cargo.toml, blowfish/src/lib.rs
This should not break the public api if I'm not mistaken due to the default type parameter but I changed the dependencies so I'm not sure if thats a breaking change in a way.
Added the typedefs since something like that was mentioned in the issue. Not sure if they really are needed though cause one could just use the type parameters without adding many more characters.
Closes #26
=> Make blowfish generic over ByteOrder

blowfish/src/lib.rs, cast5/src/lib.rs, des/src/lib.rs, magma/src/lib.rs, rc2/src/lib.rs, serpent/src/lib.rs, twofish/src/lib.rs
`#![forbid(unsafe_code)]` attributes make rustc abort compilation if
there are any unsafe blocks in the crate, and exceptions cannot be made
with allow/warn attributes.
Also add badges on README.md to advertise the complete safety of the
changed crates ([rendered], tell me if it's too much i'll remove them).
[rendered]: https://github.com/hhirtz/block-ciphers/blob/blowfish-unsafe/README.md#supported-algorithms
=> Forbid unsafe code where possible

serpent/CHANGELOG.md, serpent/Cargo.toml, serpent/README.md, serpent/src/lib.rs
=> serpent v0.0.1

Cargo.lock, block-modes/Cargo.toml, block-modes/src/cbc.rs, block-modes/src/ecb.rs, block-modes/src/errors.rs, block-modes/src/lib.rs, block-modes/src/pcbc.rs, block-modes/src/traits.rs, block-modes/src/utils.rs, block-modes/tests/lib.rs
=> block-modes: 2018 edition and `block-cipher` crate upgrade

Cargo.lock, block-modes/src/lib.rs, blowfish/Cargo.toml, blowfish/benches/lib.rs, blowfish/src/lib.rs, blowfish/tests/lib.rs
=> blowfish: 2018 edition and `block-cipher` crate upgrade

Cargo.lock, cast5/Cargo.toml, cast5/benches/lib.rs, cast5/src/cast5.rs, cast5/src/lib.rs, cast5/src/schedule.rs, cast5/tests/lib.rs
=> cast5: 2018 edition and `block-cipher` crate upgrade

Cargo.lock, cast5/src/lib.rs, des/Cargo.toml, des/README.md, des/benches/des.rs, des/benches/tdes.rs, des/src/des.rs, des/src/lib.rs, des/src/tdes.rs, des/tests/lib.rs
=> des: 2018 edition and `block-cipher` crate upgrade

Cargo.lock, des/tests/lib.rs, idea/Cargo.toml, idea/benches/lib.rs, idea/src/lib.rs, idea/tests/lib.rs
=> idea: 2018 edition and `block-cipher` crate upgrade

Cargo.lock, kuznyechik/Cargo.toml, kuznyechik/benches/lib.rs, kuznyechik/src/lib.rs, kuznyechik/tests/lib.rs
=> kuznyechik: 2018 edition and `block-cipher` crate upgrade

Cargo.lock, magma/Cargo.toml, magma/benches/lib.rs, magma/src/construct.rs, magma/src/gen_table.rs, magma/src/lib.rs, magma/tests/lib.rs
=> magma: 2018 edition and `block-cipher` crate upgrade

Cargo.lock, rc2/Cargo.toml, rc2/benches/lib.rs, rc2/src/lib.rs, rc2/tests/lib.rs
=> rc2: 2018 edition and `block-cipher` crate upgrade

Cargo.lock, serpent/Cargo.toml, serpent/src/lib.rs, serpent/tests/lib.rs
Upgrades to the (now 2018 edition) `block-cipher` crate (formerly `block-cipher-trait`).
=> serpent: `block-cipher` crate upgrade

blowfish/Cargo.toml, cast5/Cargo.toml, des/Cargo.toml, idea/Cargo.toml, magma/Cargo.toml, rc2/Cargo.toml, serpent/Cargo.toml, twofish/Cargo.toml
We've migrated to GitHub Actions.
Also it seems the badges feature of crates.io has been removed entirely(!):
https://github.com/rust-lang/crates.io/issues/2436
=> Cargo.toml(s): remove Travis CI badges

threefish/Cargo.toml, threefish/benches/lib.rs, threefish/src/lib.rs
=> threefish: 2018 edition and `block-cipher` crate upgrade

Cargo.lock, twofish/Cargo.toml, twofish/benches/lib.rs, twofish/src/lib.rs, twofish/tests/lib.rs
=> twofish: 2018 edition and `block-cipher` crate upgrade

Cargo.lock, aes/Cargo.toml, aes/aes-soft/Cargo.toml, aes/aesni/Cargo.toml, block-modes/Cargo.toml, block-modes/src/lib.rs, block-modes/tests/lib.rs, cast5/Cargo.toml, des/Cargo.toml, idea/Cargo.toml, kuznyechik/Cargo.toml, magma/Cargo.toml, rc2/Cargo.toml, serpent/Cargo.toml, sm4/Cargo.toml, threefish/Cargo.toml, twofish/Cargo.toml
...to reflect the breaking 2018 edition and `block-cipher` updates
=> Bump all versions to `*-pre`

.github/workflows/workspace.yml, aes/aes-soft/src/bitslice.rs, aes/aes-soft/src/consts.rs, aes/aes-soft/src/expand.rs, aes/aes-soft/src/impls.rs, aes/aesni/src/aes128.rs, aes/aesni/src/aes128/expand.rs, aes/aesni/src/aes192.rs, aes/aesni/src/aes192/expand.rs, aes/aesni/src/aes256.rs, aes/aesni/src/aes256/expand.rs, aes/aesni/src/ctr.rs, blowfish/src/consts.rs, blowfish/src/lib.rs, cast5/src/consts.rs, des/src/consts.rs, des/src/des.rs, idea/src/lib.rs, kuznyechik/src/lib.rs, serpent/src/lib.rs, sm4/src/lib.rs, threefish/src/consts.rs, twofish/src/consts.rs, twofish/src/lib.rs
This commit allows this workspace to pass `cargo clippy`, either by applying clippy's advice, or whitelisting the code with `#[clippy::*]` attributes.
=> Fix or whitelist clippy nits

aes/aes-soft/src/impls.rs, aes/aesni/src/aes128.rs, aes/aesni/src/aes192.rs, aes/aesni/src/aes256.rs, aes/aesni/src/ctr.rs, aes/aesni/src/utils.rs, blowfish/src/lib.rs, cast5/src/cast5.rs, des/src/des.rs, des/src/lib.rs, des/src/tdes.rs, idea/src/lib.rs, kuznyechik/src/lib.rs, magma/src/lib.rs, rc2/src/lib.rs, serpent/src/lib.rs, sm4/src/lib.rs, threefish/src/lib.rs, twofish/src/lib.rs
This is a re-export of `typenum::consts` which is more convenient than `block_cipher::generic_array::typenum::*`.
Inspired by a similar pattern in the `heapless` crate.
=> Use `block_cipher::consts::*`

README.md
No longer needed in the 2018 edition.
=> README.md: get rid of extern crate directives

aes/aesni/src/aes128/expand.rs, aes/aesni/src/aes192/expand.rs, aes/aesni/src/aes256/expand.rs, aes/aesni/src/ctr.rs
Resolves clippy lints about soundness, and will be optimized away by the compiler:
https://rust.godbolt.org/z/inEYXR
=> aesni: use MaybeUninit::zeroed() to init XMM registers

.github/workflows/security-audit.yml, Cargo.toml
This is needed to pull them in as a git dependency
=> Cargo.toml: add `aes-soft` and `aesni` crates to workspace

.github/workflows/block-modes.yml, Cargo.lock, block-modes/Cargo.toml, block-modes/src/cfb.rs, block-modes/src/cfb8.rs, block-modes/src/errors.rs, block-modes/src/lib.rs, block-modes/src/ofb.rs, block-modes/src/traits.rs, block-modes/tests/lib.rs
Those modes are often used with padding, even though they can be used as stream ciphers. We could wrap `StreamCipher + FromBlockCipher`, but it will be more convoluted and a bit less efficient.
This PR also adds `alloc` feature and removes `Error::description` impl.
I am not 100% confident in the CFB parallel code, so it should be properly covered by tests.
=> Return CFB and OFB modes

aes/README.md, blowfish/README.md, cast5/README.md, des/README.md, idea/README.md, kuznyechik/README.md, magma/README.md, rc2/README.md, serpent/README.md, sm4/README.md, threefish/README.md, twofish/README.md
Spelling error: "integerity" -> "integrity"
=> README.md(s): fix typo

magma/tests/lib.rs
For whatever reason rustfmt wants to aggressively strip trailing comments.
This adds a small hack to preserve the commented-out code.
=> magma: fix rustfmt

Cargo.lock, aes/aesni/Cargo.toml, aes/aesni/src/ctr.rs
Impls the new `FromBlockCipher` trait introduced in:
https://github.com/RustCrypto/traits/pull/164
=> aesni: impl FromBlockCipher for AES-CTR types

Cargo.lock, aes/CHANGELOG.md, aes/Cargo.toml, aes/aes-soft/CHANGELOG.md, aes/aes-soft/Cargo.toml, aes/aesni/CHANGELOG.md, aes/aesni/Cargo.toml, block-modes/Cargo.toml
Releases the following versions of the `aes/` crates:
- `aes` v0.4.0
- `aes-soft` v0.4.0
- `aesni` v0.7.0
=> aes: release new crates

Cargo.lock, block-modes/CHANGELOG.md, block-modes/Cargo.toml
- Upgrade to Rust 2018 edition ([#87])
- Bump `block-cipher` dependency to v0.7 ([#87])
[#87]: https://github.com/RustCrypto/block-ciphers/pull/87
Closes #127
=> block-modes v0.4.0

Cargo.lock, aes/aesni/CHANGELOG.md, blowfish/CHANGELOG.md, blowfish/Cargo.toml, cast5/CHANGELOG.md, cast5/Cargo.toml, des/CHANGELOG.md, des/Cargo.toml, idea/CHANGELOG.md, idea/Cargo.toml, kuznyechik/CHANGELOG.md, magma/CHANGELOG.md, rc2/CHANGELOG.md, rc2/Cargo.toml, serpent/CHANGELOG.md, serpent/Cargo.toml, sm4/CHANGELOG.md, sm4/Cargo.toml, threefish/CHANGELOG.md, threefish/Cargo.toml, twofish/CHANGELOG.md, twofish/Cargo.toml
This commit cuts releases of the following crates:
- `blowfish` v0.5.0
- `cast5` v0.7.0
- `des` v0.4.0
- `idea` v0.1.0
- `rc2` v0.4.0
- `serpent` v0.1.0
- `sm4` v0.1.0
- `twofish` v0.3.0
- `threefish` v0.1.0
It also adds CHANGELOG.md details to `kuznyechik` and `magma` but does not release those yet as they had endianness issues we should double check are corrected before cutting a release.
=> Release new crates after 2018 edition / block-cipher v0.7 upgrade

.github/workflows/kuznyechik.yml, kuznyechik/Cargo.toml, kuznyechik/src/lib.rs, kuznyechik/src/macros.rs
On my notebook I get the following results:
```
// with loop unrolling
test decrypt ... bench:         736 ns/iter (+/- 37) = 21 MB/s
test encrypt ... bench:         526 ns/iter (+/- 62) = 30 MB/s
// without loop unrolling
test decrypt ... bench:       1,237 ns/iter (+/- 71) = 12 MB/s
test encrypt ... bench:         996 ns/iter (+/- 165) = 16 MB/s
```
Unrolling can be disabled by enabling the new `no_unroll` feature.
=> Unroll loops for additional performance

gost-modes/src/cbc.rs, gost-modes/src/cfb.rs, gost-modes/src/ctr.rs, gost-modes/src/errors.rs, gost-modes/src/lib.rs, gost-modes/src/ofb.rs
Parameter `S` (number of block bytes used for message processing) is now a runtime parameter. It simplifies type signatures a bit.
=> Simplify gost-modes a bit

aes/aesni/src/target_checks.rs
"enviromental variable" -> "environment variable"
=> Fix typo in error message.

aes/aes-soft/src/bitslice.rs, aes/aes-soft/src/expand.rs, block-modes/src/traits.rs
Improved performance for the aes_soft AES implementation:
- rewrite of mix_columns to remove duplicate expressions and clarify.
- rewrite of inv_mix_columns to remove duplicate expressions and reduce overall operations.
- rewrite (inv_)shift_row methods for u16 to use "delta swaps", saving several operations.
- a small tweak to inv_mcol, used only for the decryption key schedule.
=> Performance improvements in aes_soft

aes/aesni/src/aes128.rs, aes/aesni/src/aes192.rs, aes/aesni/src/aes256.rs
When built with nocheck feature, the AES-NI intrinsics are not inlined causing a severe performance drop. (https://github.com/rust-lang/rust/issues/53069)
When compiled with `--features=nocheck`, improvement is notable (all numbers MB/s as reported by `cargo bench` on an i7-10510U, rustc 1.47)
| Benchmark | Current master (+aes) | Current master (nocheck) | This PR (nocheck) |
-----------------| ---------------------| --------------------| --------------------
| aes128_encrypt | 615 | 285 | 516 |
| aes128_encrypt8 | 2782 | 551 | 2327 |
| aes192_encrypt | 533 | 242 | 444 |
| aes192_encrypt8 | 2327 | 462 | 2000 |
| aes256_encrypt | 457 | 210 | 400 |
| aes256_encrypt8 | 2000 | 393 | 1753 |
When compiled with `RUSTFLAGS="-C target-feature=+aes,+ssse3"` there was no performance change (based …
=> aesni: Add target_feature annotations to allow intrinsic inlining

aes/aesni/src/lib.rs, gost-modes/src/lib.rs
Fixes links to obsolete crates (`block-cipher-traits`, `stream-cipher`)
=> aesni/gost-modes: rustdoc fixups

aes/aes-soft/src/bitslice.rs
Uses a more efficient algorithm for:
- bit_slice_4x4_with_u16
- un_bit_slice_4x4_with_u16
=> Perf. opt. for 1-block (un)bitslice

aes/aes-soft/benches/aes128.rs, aes/aes-soft/benches/aes256.rs, aes/aes-soft/src/fixslice.rs, aes/aes-soft/src/lib.rs, aes/aes-soft/tests/lib.rs
Closes #162
Translates the portable C implementation of the "fixslicing" technique described in:
https://eprint.iacr.org/2020/1123.pdf
Note that the reference implementation only supports AES-128/AES-256 *encryption*.
=> aes-soft: fixslicing

aes/aes-soft/benches/aes192.rs, aes/aes-soft/src/fixslice.rs, aes/aes-soft/src/lib.rs, aes/aes-soft/tests/lib.rs
@tarcieri I figured it's easier to PR this against the current master and let you integrate it into #176 .
=> aes-soft: fixslicing for AES-192 encryption

aes/aes-soft/src/bitslice.rs, aes/aes-soft/src/simd.rs
Uses a more efficient algorithm for:
- bit_slice_1x128_with_u32x4
- un_bit_slice_1x128_with_u32x4
Bit slicing can appear as an opaque series of magical masking and shifting, so I've also added comments explaining the algorithm in terms of bit index manipulation.
According to the benchmarks, the overall performance improvement is a few percent. It would be nice to benchmark the (un)bitslicing specifically, but I'm a relative rust beginner, so if anyone could help me setting that up, it would be much appreciated.
=> Perf. opt. for 8-block (un)bitslice

Cargo.lock, aes/aes-soft/CHANGELOG.md, aes/aes-soft/Cargo.toml
- Use fixslicing for AES encryption - 3X performance boost ([#174], [#176], [#177])
- Additional bitslicing performance optimizations ([#171], [#175])
[#177]: https://github.com/RustCrypto/block-ciphers/pull/177
[#176]: https://github.com/RustCrypto/block-ciphers/pull/176
[#175]: https://github.com/RustCrypto/block-ciphers/pull/175
[#174]: https://github.com/RustCrypto/block-ciphers/pull/174
[#171]: https://github.com/RustCrypto/block-ciphers/pull/171
=> aes-soft v0.6.1

aes/aes-soft/src/fixslice32.rs, aes/aes-soft/src/fixslice64.rs, aes/aes-soft/src/impls.rs, aes/aes-soft/src/lib.rs
- protoype: replaces 32-bit in lib.rs, impls.rs
Not familiar enough with rust to attempt configuration settings.
=> Add  64-bit fixslice AES implementation

.github/workflows/aes-soft.yml, aes/aes-soft/src/lib.rs
Adds CI for the `i686-unknown-linux-gnu` platform
=> aes-soft: CI for 32-bit Linux

aes/aes-soft/src/fixslice32.rs, aes/aes-soft/src/fixslice64.rs
Not just reformatting! Improved formula for the several MixColumn variants needed by the fixslice AES with fewer operations and less data dependencies.
@aadomn Although I've done these somewhat intuitively, I believe they can be derived (e.g. for the first-round MixColumns) by grouping the initial equations of [Figure 6](https://eprint.iacr.org/2020/1123.pdf) using:
`rot_cols_2(rot_rows_2(x)) ^ rot_cols_1(rot_rows_3(x)) == rot_cols_2(rot_rows_2(x ^ rot_cols_3(rot_rows_1(x))))`
EDIT: Corrected equation.
=> Improved AES fixslice MixColumns algorithm(s)

aes/aes-soft/src/fixslice32.rs, aes/aes-soft/src/fixslice64.rs
The fixsliced implementations now support encryption and decryption.
=> aes-soft: fix comment

Cargo.lock, aes/aes-soft/CHANGELOG.md, aes/aes-soft/Cargo.toml
- 64-bit fixsliced AES implementation ([#180])
- Fixsliced AES decryption ([#185])
- Improved AES fixsliced MixColumns algorithms ([#184])
[#185]: https://github.com/RustCrypto/block-ciphers/pull/185
[#184]: https://github.com/RustCrypto/block-ciphers/pull/184
[#180]: https://github.com/RustCrypto/block-ciphers/pull/180
=> aes-soft v0.6.2

aes/aes-soft/src/lib.rs
We don't have to retain this in perpetuity, but now that the implementation is fully safe code, adding this attribute gets a 🔒 in [cargo-geiger](https://github.com/rust-secure-code/cargo-geiger):
=> aes-soft: forbid unsafe

aes/aes-soft/src/fixslice32.rs, aes/aes-soft/src/fixslice64.rs
- Rename methods for consistency with AES specification
- De-unroll several loops
- Macro-ize the (inv_)mix_columns definitions
@tarcieri Let me know if you see anything else annoying and I can add it here too.
=> Comprehensive refactoring of fixslice code

Cargo.lock, aes/aes-soft/CHANGELOG.md, aes/aes-soft/Cargo.toml
- Comprehensive refactoring of fixslice code ([#192])
- Forbid `unsafe` ([#190])
- Re-order (`inv`)`_sbox` using custom scheduler ([#189])
[#192]: https://github.com/RustCrypto/block-ciphers/pull/192
[#190]: https://github.com/RustCrypto/block-ciphers/pull/190
[#189]: https://github.com/RustCrypto/block-ciphers/pull/189
=> aes-soft v0.6.3

.github/workflows/aes-soft.yml, aes/aes-soft/Cargo.toml, aes/aes-soft/src/fixslice32.rs, aes/aes-soft/src/fixslice64.rs
- under cfg feature 'semi_fixslice'
- reduces code size at small cost to performance
Alternative, slightly simpler variant described in [the paper](https://eprint.iacr.org/2020/1123). I'm not sure if this is the ideal way to present the alternative, but it gets working code in place.
=> Implement alternative semi-fixslice

aes/aes-soft/src/fixslice32.rs, aes/aes-soft/src/fixslice64.rs, aes/aes-soft/src/lib.rs
- also tweak the lib.rs cfg for fixslice
Results in significant speedup for aes128 and aes256 key schedules.
=> Rework of xor_columns in fixslice

Cargo.lock, aes/aes-soft/CHANGELOG.md, aes/aes-soft/Cargo.toml
- Rework of xor_columns ([#197])
- Implement semi-fixsliced support under `semi_fixslice` Cargo feature ([#195])
[#197]: https://github.com/RustCrypto/block-ciphers/pull/197
[#195]: https://github.com/RustCrypto/block-ciphers/pull/195
=> aes-soft v0.6.4

.github/workflows/aes.yml, aes/Cargo.toml, aes/src/lib.rs, aes/src/soft/fixslice32.rs, aes/src/soft/fixslice64.rs
The "semi_fixslice" name is jargon and doesn't describe what the feature does, which is reduce code size.
This commit renames it to describe what the feature does: make code "compact".
=> aes: rename `semi_fixslice` feature to `compact`

.github/workflows/aes.yml
AES-NI support was not being properly tested on both 32-bit and 64-bit targets.
Also adds better testing for various feature combinations.
=> aes: CI config cleanups

.github/workflows/aes.yml, Cargo.lock, aes/Cargo.toml, aes/src/autodetect.rs, aes/src/lib.rs, aes/src/ni/aes128.rs, aes/src/ni/aes192.rs, aes/src/ni/aes256.rs, aes/src/soft/fixslice64.rs, aes/src/soft/impls.rs
Closes #25.
Adds an off-by-default `autodetect` feature which the `cpuid-bool` crate to detect whether AES-NI is available when compiling on i686/x86_64 architectures.
=> aes: autodetection support for AES-NI

aes/src/autodetect.rs
The accelerated AES-CTR implementation in this crate makes use of SSSE3 instructions.
Though in theory all CPUs with AES-NI should have SSSE3, the `aes` target feature does not implicitly enable SSSE3 per the Rust Reference:
https://doc.rust-lang.org/reference/attributes/codegen.html#x86-or-x86_64
...so this separate check ensures the availability of SSSE3.
=> aes: detect AES-NI + SSSE3 for AES-CTR

aes/src/soft/impls.rs
When using the `autodetect` module, we store the possible backing AES implementations in a `union`, which presently requires all fields be `Copy` until `ManuallyDrop` stabilizes in Rust 1.49.
However, the "soft" types are directly exposed on non-x86 architectures or when the `force-soft` feature is enabled. Having these types be `Copy` when the autodetect wrappers aren't is inconsistent, and it's better to require an explicit clone for these to make users think when they make copies of key material.
As a workaround until `ManuallyDrop` lands, this gates the `Copy` impl on the "soft" types to only cases where it is hidden behind the autodetect facade (i.e. when they presently *need* to be `Copy`).
=> aes: remove Copy from public types of "soft" impls

.github/workflows/aes.yml, aes/README.md, aes/src/autodetect.rs, aes/src/ni/aes128.rs, aes/src/ni/aes192.rs, aes/src/ni/aes256.rs, aes/src/soft/impls.rs
Uses the new `core::mem::ManuallyDrop` feature to allow the inner types of unions to be non-`Copy`.
=> aes: make autodetect unions non-Copy; MSRV 1.49+

.github/workflows/block-modes.yml, .github/workflows/blowfish.yml, .github/workflows/cast5.yml, .github/workflows/des.yml, .github/workflows/gost-modes.yml, .github/workflows/idea.yml, .github/workflows/kuznyechik.yml, .github/workflows/magma.yml, .github/workflows/rc2.yml, .github/workflows/serpent.yml, .github/workflows/sm4.yml, .github/workflows/threefish.yml, .github/workflows/twofish.yml, block-modes/README.md
The tests are failing because the `aes` crate now uses `ManuallyDrop` unions which are MSRV 1.49 (see #216)
=> block-modes: bump MSRV to 1.49+

.github/workflows/block-modes.yml, block-modes/Cargo.toml, block-modes/README.md
As @newpavlov pointed out, the actual MSRV of this crate didn't change.
If we run tests with the `aes` crate's `force-soft` feature enabled, we can still CI with Rust 1.41.
=> block-modes: MSRV 1.41

.github/workflows/aes.yml, aes/README.md
Rust 1.49 features are only needed for CPU feature autodetection.
We can still support MSRV 1.41 when the `force-soft` feature is enabled.
This commit adds CI configuration to test `force-soft` under Rust 1.41, and makes a note of Rust 1.41 support when `force-soft` is enabled.
=> aes: support MSRV 1.41 under `force-soft`

aes/src/ni/aes128.rs, aes/src/ni/aes128/expand.rs, aes/src/ni/aes192.rs, aes/src/ni/aes192/expand.rs, aes/src/ni/aes256.rs, aes/src/ni/aes256/expand.rs, aes/src/ni/utils.rs
The previous usage of macros made refactoring extremely difficult, with small changes resulting in hundrdeds upon hundreds of errors when the macros are expanded, as opposed to a single error in a particular function.
This commit replaces the AES-NI `util.rs` macros with `#[inline(always)]` functions.
There is no change to the generated assembly.
=> aes: replace AES-NI macros with inline(always) functions

aes/src/ni/aes128/expand.rs, aes/src/ni/aes192/expand.rs, aes/src/ni/aes256/expand.rs, aes/src/ni/utils.rs
- Uses array operations on the block buffer
- Uses loops where they don't appear to impact performance
=> aes: refactor NI backend

Cargo.lock, aes/Cargo.toml, block-modes/Cargo.toml, blowfish/Cargo.toml, cast5/Cargo.toml, des/Cargo.toml, gost-modes/Cargo.toml, idea/Cargo.toml, kuznyechik/Cargo.toml, magma/Cargo.toml, rc2/Cargo.toml, serpent/Cargo.toml, sm4/Cargo.toml, threefish/Cargo.toml, twofish/Cargo.toml
Release notes: https://github.com/RustCrypto/traits/pull/621
=> Bump `cipher` dependency to v0.3 release

Cargo.lock, aes/Cargo.toml, aes/src/autodetect.rs
=> aes: use `cpufeatures` v0.1 crate release

Cargo.lock, aes/Cargo.toml
Release notes: https://github.com/RustCrypto/stream-ciphers/pull/229
=> aes: bump `ctr` crate dependency to v0.7

Cargo.lock, aes/CHANGELOG.md, aes/Cargo.toml, aes/README.md, aes/src/lib.rs, block-modes/Cargo.toml
- Auto-detection support for AES-NI; MSRV 1.49+ ([#208], [#214], [#215], [#216])
- Unify the `aes`, `aesni`, and `aes-soft` crates ([#200])
- Use `cfg-if` crate ([#203])
- Rename `semi_fixslice` feature to `compact` ([#204])
- Refactor NI backend ([#224], [#225])
- Bump `cipher` crate dependency to v0.3 release ([#235])
- Bump `ctr` crate dependency to v0.7 ([#237])
[#200]: https://github.com/RustCrypto/block-ciphers/pull/200
[#203]: https://github.com/RustCrypto/block-ciphers/pull/203
[#204]: https://github.com/RustCrypto/block-ciphers/pull/204
[#208]: https://github.com/RustCrypto/block-ciphers/pull/208
[#214]: https://github.com/RustCrypto/block-ciphers/pull/214
[#215]: https://github.com/RustCrypto/block-ciphers/pull/215
[#216]: https://github.com/RustCrypto/block-ciphers/pull/216 …
=> aes v0.7.0

Cargo.lock, block-modes/CHANGELOG.md, block-modes/Cargo.toml, blowfish/CHANGELOG.md, blowfish/Cargo.toml, cast5/CHANGELOG.md, cast5/Cargo.toml, des/CHANGELOG.md, des/Cargo.toml, gost-modes/CHANGELOG.md, gost-modes/Cargo.toml, idea/CHANGELOG.md, idea/Cargo.toml, kuznyechik/CHANGELOG.md, kuznyechik/Cargo.toml, magma/CHANGELOG.md, magma/Cargo.toml, rc2/CHANGELOG.md, rc2/Cargo.toml, serpent/CHANGELOG.md, serpent/Cargo.toml, sm4/CHANGELOG.md, sm4/Cargo.toml, threefish/CHANGELOG.md, threefish/Cargo.toml, twofish/CHANGELOG.md, twofish/Cargo.toml
Releases new versions of all crates in this repository which incorporate the `cipher` v0.3 release changes (RustCrypto/traits#621)
=> Release `cipher` v0.3-based versions

aes/src/soft/fixslice32.rs, aes/src/soft/fixslice64.rs
It appears that `fixslice64.rs` was accidentally overwritten with `fixslice32.rs` in #208.
This restores the 64-bit implementation to what it was prior to that PR.
Closes #246.
=> aes: restore fixslice64.rs

aes/CHANGELOG.md, aes/Cargo.toml
- Restore `fixslice64.rs` ([#247])
[#247]: https://github.com/RustCrypto/block-ciphers/pull/247
=> aes v0.7.1

Cargo.lock, aes/src/ni.rs
These docs are leftover from the `aesni` crate and no longer describe the current state of the `aes` crate, namely that it now supports CPUID detection with a software fallback.
=> aes: remove outdated docs

.github/workflows/aes.yml, .github/workflows/workspace.yml, .gitignore, aes/Cargo.lock, aes/Cargo.toml, aes/src/armv8.rs, aes/src/autodetect.rs, aes/src/lib.rs, aes/src/ni/aes128.rs, aes/src/ni/aes192.rs, aes/src/ni/aes256.rs, aes/src/ni/utils.rs
Adds a new backend which uses ARMv8 Cryptography Extensions. These are currently unstable so support is gated under a newly added `armv8` crate feature.
These extensions are supported on both 32-bit and 64-bit ARM targets, however the current implementation is gated on `aarch64` (as that's the only architecture it's been tested on so far).
Closes #10.
=> ARMv8 Cryptography Extensions support

Cargo.lock, aes/CHANGELOG.md, aes/Cargo.toml
- Nightly-only ARMv8 intrinsics support gated under the `armv8` feature ([#250])
[#250]: https://github.com/RustCrypto/block-ciphers/pull/250
=> aes v0.7.2

aes/src/lib.rs
Fixes inconsistencies in the rustdoc relating ot the newly added ARMv8 intrinsics features.
Moves all docs relating to backends to separate subsections, and removes the superfluous/obsolete docs.
=> aes: rustdoc improvements

.github/workflows/aes.yml, aes/Cargo.lock, aes/Cargo.toml, aes/src/armv8.rs, aes/src/armv8/decrypt.rs, aes/src/armv8/encrypt.rs, aes/src/armv8/expand.rs, aes/src/armv8/round.rs, aes/src/lib.rs, aes/src/ni.rs, aes/src/ni/round.rs, aes/src/round.rs, aes/tests/round.rs
Closes #252
Exposes a `hazmat` (more like kryptonite) raw AES round function API intended for use in implementing things like CAESAR candidates (e.g. AEGIS, AEZ, Deoxys)
The current implementation only wraps hardware intrinsics and panics if they aren't available, however the goal is to provide a soft portable fallback as well.
Currently only exposes the "cipher" function (i.e. encryption). However, the goal is to support at least the "equivalent inverse cipher" function (ala Intel AES-NI's `AESDEC`) as well.
cc @zer0x64
=> aes: expose raw round function API

aes/src/armv8.rs, aes/src/armv8/hazmat.rs, aes/src/hazmat.rs, aes/src/lib.rs, aes/src/ni.rs, aes/src/ni/hazmat.rs, aes/tests/hazmat.rs
Renames the `round` module to `hazmat` to make it more general (and match the `hazmat` feature name).
Adds an `inv_mix_columns` function to it with backends for both the ARMv8 Cryptography Extensions as well as AES-NI.
cc @zer0x64
=> aes: rename `hazmat` module; add `inv_mix_columns`

aes/src/armv8/hazmat.rs, aes/src/hazmat.rs, aes/src/ni/hazmat.rs, aes/tests/hazmat.rs
Like the other functions in the `hazmat` module, this is presently an intrinsics-only implementation.
On ARMv8 we can use the dedicated `AESMC` instruction.
Intel AES-NI has no explicit instruction for mix columns, but it can be emulated by performing `AESIMC` (inverse mix columns) three times.
cc @zer0x64
=> aes: add `mix_columns` function to `hazmat` module

aes/src/lib.rs
These are a bit easier to work with versus GenericArray, and ideally also futureproof for a const generics upgrade.
=> aes: use Block and ParBlocks type aliases in rustdoc

aes/src/lib.rs, aes/src/ni/ctr.rs
I've found myself wanting this in downstream crates which consume this one. I think it could be also used in a number of places in the implementation of this crate in order to make it clearer.
It's also similar to the existing constant in the `polyval` crate:
https://docs.rs/polyval/0.5.0/polyval/constant.BLOCK_SIZE.html
=> aes: add `BLOCK_SIZE` constant

Cargo.lock, aes/CHANGELOG.md, aes/Cargo.toml, aes/src/hazmat.rs
- `hazmat` feature/module providing round function access ([#257], [#259], [#260])
- `BLOCK_SIZE` constant ([#263])
[#257]: https://github.com/RustCrypto/block-ciphers/pull/257
[#259]: https://github.com/RustCrypto/block-ciphers/pull/259
[#260]: https://github.com/RustCrypto/block-ciphers/pull/260
[#263]: https://github.com/RustCrypto/block-ciphers/pull/263
=> aes v0.7.3

aes/src/hazmat.rs, aes/src/lib.rs, aes/src/soft/fixslice32.rs, aes/src/soft/fixslice64.rs, aes/tests/hazmat.rs
Adds a preliminary module structure for supporting the low-level `hazmat` APIs in the `soft` backend.
=> aes: soft `hazmat` modules

aes/Cargo.lock, aes/src/soft/fixslice32.rs, aes/src/soft/fixslice64.rs, aes/tests/hazmat.rs
The `hazmat` API provides access to the raw AES cipher round, equivalent inverse cipher round, mix columns, and inverse mix column operations.
This PR wires up support for these operations in the "soft" backend (or more specifically, both the 32-bit and 64-bit fixsliced backends).
It would benefit from a parallel API instead of what's currently provided, however that's left for future work.
=> aes: soft `hazmat` backend

.github/workflows/aes.yml, aes/src/armv8/hazmat.rs, aes/src/hazmat.rs, aes/src/ni/hazmat.rs, aes/src/soft/fixslice32.rs, aes/src/soft/fixslice64.rs, aes/tests/hazmat.rs
Adds the following parallel APIs:
- `hazmat::cipher_round_par`
- `hazmat::equiv_inv_cipher_round_par`
These APIs operate over `ParBlocks` instead of `Blocks`, leveraging either ILP with intrinsics, or the natural parallelism that results from fixslicing.
Not much effort has been put into optimizing, nor have benchmarks been performed. This implementation is just an end-to-end spike, and probably has some room for improvement.
There's also the possibility of parallelizing `(inv_)mix_columns`, however I left that out for now as encryption/decryption seem like the important functionality to parallelize.
cc @zer0x64 @peterdettman
=> aes: add parallel `hazmat` APIs

.github/workflows/aes.yml, aes/src/hazmat.rs, aes/src/lib.rs
Now that the `hazmat` feature supports the "soft" backend, this adds additional coverage checks to ensure it works in all of the various environments we support.
=> aes: expand CI coverage for `hazmat` feature

aes/src/hazmat.rs
Simplifies runtime CPU feature-based gating inside the `hazmat` module.
=> aes: add private `if_intrinsics_available!` macro

Cargo.lock, aes/CHANGELOG.md, aes/Cargo.toml
- Soft `hazmat` backend ([#267], [#268])
- Parallel `hazmat` APIs ([#269])
[#267]: https://github.com/RustCrypto/block-ciphers/pull/267
[#268]: https://github.com/RustCrypto/block-ciphers/pull/268
[#269]: https://github.com/RustCrypto/block-ciphers/pull/269
=> aes v0.7.4

twofish/src/lib.rs
This aligns Twofish with AES.  Among other things, it allows its use
with EAX with requires Clone.
=> twofish: Derive Clone for Twofish.

blowfish/Cargo.toml
It also would be appreciated to release a new version of blockfish with an updated byteorder dependency because it's not a dev-dependency unlike other updated dependencies.
Not committing Cargo.lock is recommended, as libraries cannot really control what dependencies Cargo downloads, and as such it makes sense to test newest versions of dependencies on CI.
=> Update dependencies to build with cargo update -Z minimal-versions

Cargo.lock, aes/Cargo.toml, aes/src/armv8.rs, aes/src/autodetect.rs, aes/src/lib.rs, aes/src/ni.rs, aes/src/soft.rs
The crate feature `zeroize` was previously present, but unused.
This implements zeroization on drop for all aes types in the software and aesni implementations, if the `zeroize` feature is enabled.
**This PR does not include support for the armv8 implementation.**
I do not have access to hardware to test it and a clean implementation is also likely blocked on the zeroize crate implementing `Zeroize` for the inner `uint8x16_t` type used.
Still I thought this might be a useful patch even without armv8 support.
If you'd prefer, I can also add some documentation describing this limitation to users.
=> aes: implement `Zeroize` for aes keys

camellia/src/camellia.rs
=> Fix missing space before curly brace

aes/Cargo.toml, aes/src/lib.rs
It's been stabilized: rust-lang/rust#90620
Because of that, it's breaking the build on recent nightlies:
https://github.com/RustCrypto/block-ciphers/runs/7968517726?check_suite_focus=true#step:7:103
> error: the feature `aarch64_target_feature` has been stable since 1.61.0 and no longer requires an attribute to enable
=> aes: remove use of `aarch64_target_feature`

belt-block/src/lib.rs
New comments use notation from the spec. Also fixed typo in the encryption step 5.3.
=> belt-block: minor changes in inner docs

Cargo.lock, belt-block/CHANGELOG.md, belt-block/Cargo.toml, belt-block/README.md, belt-block/src/cipher_impl.rs, belt-block/src/lib.rs, belt-block/tests/mod.rs
Also makes implementation of the `cipher` traits gated on enabled by default `cipher` feature.
=> belt-block: add belt_block_raw function

Cargo.lock, Cargo.toml, README.md, rc5/CHANGELOG.md, rc5/Cargo.toml, rc5/README.md
- Add `rc5` to README.md table
- Bump version down to 0.0.0
- Remove unreleased entry from CHANGELOG.md
- Alphebetize Cargo.toml workspace members
=> rc5: post-merge cleanups

.github/workflows/aes.yml, aes/src/lib.rs
* Added a note about instruction-level parallelism to Examples. (#351)
* Added a space to `-Ctarget-feature=+aes,+ssse3` since having a space after `-C` seems to be the [more common form](https://doc.rust-lang.org/rustc/codegen-options/index.html#target-feature).
(`-Dwarnings` are not changed, because is seems [ignoring space after `-D` is more common](https://doc.rust-lang.org/clippy/usage.html#command-line))
=> `aes` docs update

.github/workflows/aes.yml, .github/workflows/aria.yml, .github/workflows/belt-block.yml, .github/workflows/blowfish.yml, .github/workflows/camellia.yml, .github/workflows/cast5.yml, .github/workflows/des.yml, .github/workflows/idea.yml, .github/workflows/kuznyechik.yml, .github/workflows/magma.yml, .github/workflows/rc2.yml, .github/workflows/rc5.yml, .github/workflows/serpent.yml, .github/workflows/sm4.yml, .github/workflows/speck.yml, .github/workflows/threefish.yml, .github/workflows/twofish.yml, .github/workflows/workspace.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/RustCrypto/block-ciphers/actions/runs/4369733185:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain).
=> Replace unmaintained actions-rs/toolchain action in CI workflows

Cargo.lock, threefish/CHANGELOG.md, threefish/Cargo.toml, threefish/src/lib.rs, threefish/tests/mod.rs
The changes are useful for [implementing](https://github.com/RustCrypto/hashes/pull/483) Skein.
=> threefish: add u64-based methods and make cipher optional

.github/workflows/aes.yml, aes/src/armv8.rs, aes/src/armv8/encdec.rs, aes/src/armv8/expand.rs, aes/src/armv8/hazmat.rs, aes/src/armv8/intrinsics.rs, aes/src/armv8/test_expand.rs, aes/src/lib.rs
Adds "polyfills" for the unstable ARMv8 AES intrinsics using the `asm!` macro which was stabilized in Rust 1.59. However note we also need `target_feature` stabilizations for `aes` and `neon` which occurred in Rust 1.61.
Based on benchmarks this has no effect on performance, although it was necessary to place AESE/AESMC and AESD/AESIMC into a single `asm!` block in order to ensure that instructions fuse properly, as they did when using the proper intrinsics.
In the next breaking release, we should be able to get rid of the `aes_armv8` configuration parameter entirely, bumping MSRV to 1.59 and then ARMv8 support should Just Work(TM) where available.
Performance appears to be unchanged.
```
$ RUSTFLAGS="--cfg aes_armv8" cargo +nightly bench
Compiling aes v0.8.2 …
```
=> aes: support `aes_armv8` on Rust 1.61+ using `asm!`

aes/src/armv8.rs, aes/src/armv8/expand.rs, aes/src/armv8/test_expand.rs
Changes `expand_key` to an `unsafe fn` that uses `target_feature`.
Removes the TODOs: due to AES-192 this function can't be easily refactored to use `vinterpretq_u8_u32`.
=> aes: refactor ARMv8 `expand_key`

Cargo.lock, aes/CHANGELOG.md, aes/Cargo.toml
- Support `aes_armv8` on Rust 1.61+ using `asm!` ([#365])
[#365]: https://github.com/RustCrypto/block-ciphers/pull/365
=> aes v0.8.3

Cargo.lock, kuznyechik/CHANGELOG.md, kuznyechik/Cargo.toml
- `Drop` implementations in the software backend with enabled `zeroize` feature ([#311])
[#311]: https://github.com/RustCrypto/block-ciphers/pull/311
=> Release kuznyechik v0.8.2

aes/src/armv8.rs, aes/src/ni.rs
=> aes: add #[inline] attributes for KeyInit::new impls

Cargo.lock, rc5/CHANGELOG.md, rc5/Cargo.toml, rc5/benches/mod.rs, rc5/src/block_cipher.rs, rc5/src/core/primitives.rs, rc5/src/lib.rs, rc5/tests/mod.rs
=> rc5: unlock parameter size, add u128 and u8 word size support.

.github/workflows/speck.yml, Cargo.lock, Cargo.toml, aes/src/armv8.rs, aes/src/autodetect.rs, aes/src/lib.rs, aes/src/ni.rs, aes/src/soft.rs, aria/src/lib.rs, aria/tests/mod.rs, belt-block/tests/mod.rs, camellia/src/lib.rs, cast5/src/lib.rs, cast5/tests/mod.rs, cast6/src/lib.rs, cast6/tests/mod.rs, kuznyechik/src/soft/mod.rs, kuznyechik/src/sse2/mod.rs, kuznyechik/tests/mod.rs, magma/src/lib.rs, rc2/tests/mod.rs, rc5/src/block_cipher.rs, rc5/tests/mod.rs, sm4/tests/mod.rs, speck/tests/mod.rs, threefish/tests/mod.rs, twofish/tests/mod.rs
Updates the previous `BlockEncrypt`/`BlockEncrypt` trait names to use the new ones introduced in RustCrypto/traits#1482
=> Use `BlockCipherEncrypt`/`BlockCipherDecrypt` trait names

belt-block/src/lib.rs, belt-block/tests/mod.rs
This is a breaking change, so it should be merged only as part of the next breaking release.
=> belt-block: mark `to_u32` function as private

aes/src/armv8/expand.rs
Feel free to edit, and let me know if I've missed something and this is actually guaranteed statically.
This came up [here](https://fuchsia-review.git.corp.google.com/c/fuchsia/+/987054/1/third_party/rust_crates/vendor/aes-0.8.3/src/armv8/expand.rs#26) when vendoring `aes` into Fuchsia.
=> aes: Assert precondition required for soundness

aes/CHANGELOG.md, aes/src/armv8/expand.rs
This was backported in #409.
Also includes a small comment fixup.
=> aes: add v0.8.4 CHANGELOG entry

Cargo.lock, Cargo.toml, aes/Cargo.toml, aria/Cargo.toml, belt-block/Cargo.toml, blowfish/Cargo.toml, camellia/Cargo.toml, cast5/Cargo.toml, cast6/Cargo.toml, des/Cargo.toml, idea/Cargo.toml, kuznyechik/Cargo.toml, magma/Cargo.toml, rc2/Cargo.toml, rc5/Cargo.toml, serpent/Cargo.toml, sm4/Cargo.toml, speck/Cargo.toml, threefish/Cargo.toml, twofish/Cargo.toml
=> bump `cipher` dependency to `0.5.0-pre.4`

rc2/LICENSE-APACHE, rc5/LICENSE-APACHE
The `rc2` and `rc5` crates do not currently include the full license text, which is technically required by the Apache license.
=> Include Apache license text in rc2 and rc5 crates

aes/Cargo.toml, kuznyechik/Cargo.toml, threefish/tests/mod.rs
- add `lints.rust.unexpected_cfgs` to Cargo.toml
- threefish: fix typo in `cfg(feature = "cipher")`
=> aes,kuznyechik,threefish: Rust 1.80 lint fixes

aes/Cargo.toml, belt-block/Cargo.toml, des/Cargo.toml, kuznyechik/Cargo.toml, magma/Cargo.toml
Cuts a new release of every crate which previously received a pre.0 prerelease, i.e. is used as a (dev-)dependency in downstream projects that need to be upgraded.
This includes the following:
- `aes` v0.9.0-pre.1
- `belt-block` v0.2.0-pre.1
- `des` v0.9.0-pre.1
- `kuznyechik` v0.9.0-pre.1
- `magma` v0.10.0-pre.1
=> Cut pre.1 prereleases

Cargo.lock, gift/Cargo.toml, gift/src/lib.rs, gift/tests/test.rs, xtea/Cargo.toml, xtea/tests/mod.rs
- Updates `cipher` to v0.5.0-pre.6
- Sets both crates' versions to 0.0.0
- Renames gift to `gift-cipher` which is presently unregistered
=> gift+xtea: bump dependencies

aes/src/armv8/hazmat.rs, aes/src/hazmat.rs, aes/src/lib.rs, aes/src/ni/hazmat.rs, aes/src/soft/fixslice32.rs, aes/src/soft/fixslice64.rs, aes/tests/hazmat.rs
The backends were changed to use a different number of parallel blocks, so the alias is now used only by hazmat functions.
Closes #462
=> aes: move `Block8` to the hazmat module

aes/README.md, aria/README.md, belt-block/README.md, blowfish/README.md, camellia/README.md, cast5/README.md, cast6/README.md, des/README.md, gift/README.md, idea/README.md, kuznyechik/README.md, magma/README.md, rc2/README.md, rc5/README.md, serpent/README.md, sm4/README.md, speck/README.md, threefish/README.md, twofish/README.md, xtea/README.md
- Update MSRV badges.
- Remove the text-based "documentation" link. It's redundant, especially when readme is included in crate docs.
- Remove the "Minimum Supported Rust Version" section. After update to the 2024 edition we have a more relaxed MSRV policy, so the MSRV badge should be sufficient.
- Remove the "SemVer Policy" section. After the MSRV policy change we have the default SemVer policy (i.e. all features and public APIs are subject to SemVer), so we do not need to say it explicitly.
=> Update crate READMEs

Cargo.lock, aes/Cargo.toml, aria/Cargo.toml, belt-block/Cargo.toml, blowfish/Cargo.toml, camellia/Cargo.toml, cast5/Cargo.toml, cast6/Cargo.toml, des/Cargo.toml, gift/Cargo.toml, idea/Cargo.toml, kuznyechik/Cargo.toml, magma/Cargo.toml, rc2/Cargo.toml, rc5/Cargo.toml, serpent/Cargo.toml, sm4/Cargo.toml, speck/Cargo.toml, threefish/Cargo.toml, twofish/Cargo.toml, xtea/Cargo.toml
Also includes `rc.0` releases of crates which were previously released as `pre.3` (i.e. ones which are used as `dev-dependencies` elsewhere in the project)
=> Bump `cipher` to v0.5.0-rc.0

Cargo.lock, Cargo.toml, aes/tests/mod.rs, blowfish/tests/mod.rs, camellia/tests/mod.rs, cast5/tests/mod.rs, des/tests/mod.rs, idea/tests/mod.rs, serpent/tests/mod.rs
The upstream changes also includes RustCrypto/traits#1916, so until the tests are updated this temporarily disables them
=> Bump `hybrid-array` to v0.4
